<?php

namespace AppBundle\Repository;

/**
 * Chef_departmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Chef_departmentRepository extends \Doctrine\ORM\EntityRepository
{
}
