<?php

namespace AppBundle\Repository;

/**
 * devalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class devalRepository extends \Doctrine\ORM\EntityRepository
{
}
