<?php

namespace AppBundle\Repository;

/**
 * Enseignants_titulaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Enseignants_titulaireRepository extends \Doctrine\ORM\EntityRepository
{


    public function findTeacherPerSchool($dev)
    {

        $queryB = $this->createQueryBuilder('a');
        $queryB->select('t')
            ->from('AppBundle:Enseignants_titulaire', 't')
            ->Join('t.teacher', 's')
            ->where('s.etablissements = :dev')
            ->setParameter('dev', $dev);
        return $queryB;
    }

}
