<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Matieres;
use AppBundle\Entity\Classes;
use Doctrine\DBAL\Types\StringType;

/**
 * EpreuvesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpreuvesRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllWithCountry(Matieres $matieres, Classes $classes, StringType $type){

        return $this->createQueryBuilder('e')
            ->select('e, m, c, n')
            ->join('e.matieres', 'm')
            ->join('m.name', 'nom')
            ->join('e.classes', 'c')
            ->join('c.name', 'nomc')
            ->getQuery()
            ->getResult();
    }
}
