<?php

namespace AppBundle\Repository;

/**
 * EtablissementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementsRepository extends \Doctrine\ORM\EntityRepository
{

    public function findWithCountry(int $id){

        return $this->createQueryBuilder('e')
        ->select('e, v, d, r, c')
            ->join('e.city', 'v')
            ->join('v.departments', 'd')
            ->join('d.regions', 'r')
            ->join('r.country', 'c')
            ->where('e.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult();
    }

    public function findAllWithCountry(){

        return $this->createQueryBuilder('e')
            ->select('e, v, d, r, c')
            ->join('e.city', 'v')
            ->join('v.departments', 'd')
            ->join('d.regions', 'r')
            ->join('r.country', 'c')
            ->getQuery()
            ->getResult();
    }
}
