<?php

namespace AppBundle\Repository;

/**
 * Events_extracurricularRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Events_extracurricularRepository extends \Doctrine\ORM\EntityRepository
{
}
