<?php

namespace AppBundle\Repository;

/**
 * Facteurs_disciplinairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Facteurs_disciplinairesRepository extends \Doctrine\ORM\EntityRepository
{
}
