<?php

namespace AppBundle\Repository;

/**
 * Fiche_parentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Fiche_parentsRepository extends \Doctrine\ORM\EntityRepository
{
}
