<?php

namespace AppBundle\Repository;

/**
 * FloreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FloreRepository extends \Doctrine\ORM\EntityRepository
{
}
