<?php

namespace AppBundle\Repository;

/**
 * SectionEducRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionEducRepository extends \Doctrine\ORM\EntityRepository
{
}
