<?php

namespace AppBundle\Repository;

/**
 * studentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentsRepository extends \Doctrine\ORM\EntityRepository
{

    /*public function findByStudents($dev, $flo)
    {

        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.class.niveau.name = :dev')
            ->andWhere('u.class.name = :flo')
            ->orderBy('u.id')
            ->setParameters(array(':flo'=> $flo , ':dev' => $dev));


        return $qb->getQuery()->getResult();
    }*/
}
