<?php

namespace AppBundle\Repository;

/**
 * SysEducRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SysEducRepository extends \Doctrine\ORM\EntityRepository
{
}
