<?php

namespace AppBundle\Repository;

/**
 * TeacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherRepository extends \Doctrine\ORM\EntityRepository
{

    public function getTeacherPerSchool($dev)
    {

        $queryB=$this->createQueryBuilder('a');
        $queryB      ->select('t')
            ->from('AppBundle:Teacher', 't')
            ->where('t.etablissements = :dev')
            ->setParameter('dev', $dev);
        return $queryB;
    }

}
