<?php

namespace AppBundle\Repository;

/**
 * Type_etablissementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_etablissementsRepository extends \Doctrine\ORM\EntityRepository
{
}
